export const ALL_ORGS_RECEIVED = 'ALL_ORGS_RECEIVED'
export const ORG_DETAILS_RECEIVED = 'ORG_DETAILS_RECEIVED'
export const DONATION_ORGS_RECEIVED = 'DONATION_ORGS_RECEIVED'
export const FILTER_ORGS = 'FILTER_ORGS'

export const ALL_IDEAS_RECEIVED = 'ALL_IDEAS_RECEIVED'
export const IDEA_DETAILS_RECEIVED = 'IDEA_DETAILS_RECEIVED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const CLEAR_ORG_DETAILS = 'CLEAR_ORG_DETAILS'
export const CLEAR_IDEA_DETAILS = 'CLEAR_IDEA_DETAILS'

export const ALL_RECENT_ARTICLES_RECEIVED = 'ALL_RECENT_ARTICLES_RECEIVED'
export const MONTH_LINKS_RECEIVED = 'MONTH_LINKS_RECEIVED'
export const ALL_OLDER_POSTS_RECEIVED = 'ALL_OLDER_POSTS_RECEIVED'
export const NEWS_DETAILS_RECEIVED = 'NEWS_DETAILS_RECEIVED'

export const FILTER_DONATION_ORGS = 'FILTER_DONATION_ORGS'
export const ADD_COMMENT  = 'ADD_COMMENT'