export const ALL_ORGS_RECEIVED = 'ALL_ORGS_RECEIVED'
export const ORG_DETAILS_RECEIVED = 'ORG_DETAILS_RECEIVED'
export const DONATION_ORGS_RECEIVED = 'DONATION_ORGS_RECEIVED'

export const ALL_IDEAS_RECEIVED = 'ALL_IDEAS_RECEIVED'
export const IDEA_DETAILS_RECEIVED = 'IDEA_DETAILS_RECEIVED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'